version: '3.1'
services:
    mysql:
        container_name: MYSQL_HTTP
        image: 'mysql:8.0'
        environment:
            - MYSQL_USER=http
            - MYSQL_PASSWORD=http
            - MYSQL_ROOT_PASSWORD=MYSQL_DATABASE
            - MYSQL_DATABASE=MYSQL_DATABASE
        ports:
            - '8001:3306'
